version : "3"
services:
    multiverse-api:
        build:
            context: .
            dockerfile: Dockerfile
            args:
                PORT: 8080
        container_name: multiverse-api
        depends_on:
            - multiverse-api-pg
        volumes:
            - .:/var/www/html
        restart: always
        ports:
            - "224:80"
            - "225:191"
        environment:
            APP_NAME: 'Multiverse API'
            APP_DEBUG: 'true'
            APP_URL: 'http://24.87.1.1'
            DB_CONNECTION: 'pgsql'
            QUEUE_CONNECTION: 'database'
            XDEBUG_CONFIG: "mode=debug,coverage,develop client_host=host.docker.internal discover_client_host=1 start_with_request=yes"
        networks:
            multiverse-api-network:
                ipv4_address: 24.87.1.1
        extra_hosts:
            - host.docker.internal:host-gateway

    multiverse-api-pg:
        image: postgres:latest
        mem_limit: 1024m
        ports:
            - "226:5432"
        environment:
            POSTGRES_PASSWORD: docker
            POSTGRES_DB: multiverse
        container_name: multiverse-api-pg
        volumes:
            - multiverse-api-pg-disk:/var/lib/postgres
        command: postgres -c max_locks_per_transaction=128
        networks:
            multiverse-api-network:
                ipv4_address: 24.87.1.2

# On-disk storage of DB data, when containers are stopped
volumes:
    multiverse-api-pg-disk: {}

# Local network for services running using this docker-compose config
networks:
    multiverse-api-network:
        ipam:
            driver: default
            config:
                - subnet: 24.87.0.0/16
